steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.worker
      - -t
      - us-central1-docker.pkg.dev/keep-calm-database/call-intelligence-agent/call-intelligence-worker:latest
      - .

images:
  - us-central1-docker.pkg.dev/keep-calm-database/call-intelligence-agent/call-intelligence-worker:latest
