substitutions:
  _REGION: us-central1
  _REPOSITORY: call-intelligence-agent
  _RECEIVER_IMAGE: receiver
  _WORKER_IMAGE: worker

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.receiver
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_RECEIVER_IMAGE}:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.worker
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:$SHORT_SHA
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_RECEIVER_IMAGE}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:$SHORT_SHA
